import os
# This is needed to run tests from the root directory
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from agents.code_review_agent import CodeReviewAgent
from agents.code_quality_agent import CodeQualityAgent
from agents.docs_agent import DocsAgent
from agents.learning_agent import LearningAgent

# Sample bad code with multiple issues
sample_code_diff = """
+def very_long_function_with_bad_name(data):
+    # This function is way too long and does too many things.
+    # It also has a hardcoded password.
+    password = "password123" 
+    if len(data) > 10:
+        if 'special' in data:
+            # Deeply nested condition
+            result = data['special'] * 5
+            # No error handling for this risky operation
+            dangerous_value = result / 0
+            return dangerous_value
+    # ... more lines to make it over 50 lines
+    # ...
+    # ...
+    # ... (imagine 40 more lines of complex logic)
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+    # ...
+-    return None
"""

def run_tests():
    """Initializes and runs all agents on the sample code."""
    # Ensure you have a .env file with GROQ_API_KEY in the root
    
    print("--- Running Code Review Agent ---")
    review_agent = CodeReviewAgent()
    review_result = review_agent.review(sample_code_diff)
    print(review_result)

    print("\n--- Running Code Quality Agent ---")
    quality_agent = CodeQualityAgent()
    quality_result = quality_agent.analyze(sample_code_diff)
    print(quality_result)

    print("\n--- Running Docs Agent ---")
    docs_agent = DocsAgent()
    docs_result = docs_agent.check(sample_code_diff)
    print(docs_result)

    print("\n--- Running Learning Agent ---")
    learning_agent = LearningAgent()
    learning_result = learning_agent.learn(sample_code_diff)
    print(learning_result)

if __name__ == "__main__":
    run_tests()
